baseURL = "/"
languageCode = "fr-fr"
title = "Portfolio de Stéphan Uniatowitz - Expert Support Technique & Infrastructure"
theme = "blowfish"
relativeURLs = true

[params]
  description = "Portfolio technique de Stéphan Uniatowitz - Expert support N2/N3, réseaux et systèmes avec 85% de taux de résolution en environnements critiques"
  keywords = ["support technique", "réseaux", "systèmes", "GLPI", "VPN", "infrastructure", "technicien IT"]

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  name = "Projets"
  url = "/projets"
  weight = 1
[[menu.main]]
  name = "Compétences"
  url = "/skills"
  weight = 2
[[menu.main]]
  name = "Blog"
  url = "/blog"
  weight = 3
[[menu.main]]
  name = "À Propos"
  url = "/about"
  weight = 4
[[menu.main]]
  name = "Contact"
  url = "/contact"
  weight = 5
